listen_addr = ':8399'
cmc_rest_addr = 'localhost:8765'


[crypto.kaspa]
mainnet_rpc = 'https://api.kaspa.org'

[crypto.bitcoin]
mainnet_rpc = 'electrum.blockstream.info:50001'
testnet_rpc = 'electrum.blockstream.info:60001'

[crypto.litecoin]
mainnet_rpc = 'electrum-ltc.bysh.me:50001'
testnet_rpc = 'electrum-ltc.bysh.me:51001'

[crypto.ethereum]
mainnet_rpc = 'https://eth.llamarpc.com'
testnet_rpc = 'https://eth-sepolia.public.blastapi.io'

[crypto.solana]
mainnet_rpc = 'https://api.mainnet-beta.solana.com'
testnet_rpc = 'https://api.testnet.solana.com'
