listen_addr = ':8399'
cmc_rest_addr = '192.168.2.71:8765'
bitcoin_rpc = 'electrum.blockstream.info:50001'
ethereum_rpc = 'https://eth.llamarpc.com'
ethereum_testnet_rpc = 'https://eth-sepolia.public.blastapi.io'
solana_rpc = 'https://api.mainnet-beta.solana.com'
solana_testnet_rpc = 'https://api.testnet.solana.com'
