// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 
 *
 * API version: 1.0.2
 */

package cryptowalletrest

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	BalancesPost(http.ResponseWriter, *http.Request)
	TransactionsGet(http.ResponseWriter, *http.Request)
	UnsignedTxGet(http.ResponseWriter, *http.Request)
	BroadcastPost(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	BalancesPost(context.Context, BalancesPostRequest) (ImplResponse, error)
	TransactionsGet(context.Context, string, string, int32, int32) (ImplResponse, error)
	UnsignedTxGet(context.Context, string, string, string, string, float64) (ImplResponse, error)
	BroadcastPost(context.Context, BroadcastPostRequest) (ImplResponse, error)
}
