// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 
 *
 * API version: 1.0.2
 */

package cryptowalletrest

import (
	"encoding/json"
	"net/http"
	"strings"
)

// DefaultAPIController binds http requests to an api service and writes the service results to the http response
type DefaultAPIController struct {
	service DefaultAPIServicer
	errorHandler ErrorHandler
}

// DefaultAPIOption for how the controller is set up.
type DefaultAPIOption func(*DefaultAPIController)

// WithDefaultAPIErrorHandler inject ErrorHandler into controller
func WithDefaultAPIErrorHandler(h ErrorHandler) DefaultAPIOption {
	return func(c *DefaultAPIController) {
		c.errorHandler = h
	}
}

// NewDefaultAPIController creates a default api controller
func NewDefaultAPIController(s DefaultAPIServicer, opts ...DefaultAPIOption) *DefaultAPIController {
	controller := &DefaultAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultAPIController
func (c *DefaultAPIController) Routes() Routes {
	return Routes{
		"BalancesGet": Route{
			"BalancesGet",
			strings.ToUpper("Get"),
			"/balances",
			c.BalancesGet,
		},
		"TransactionsGet": Route{
			"TransactionsGet",
			strings.ToUpper("Get"),
			"/transactions",
			c.TransactionsGet,
		},
		"UnsignedTxGet": Route{
			"UnsignedTxGet",
			strings.ToUpper("Get"),
			"/unsigned-tx",
			c.UnsignedTxGet,
		},
		"BroadcastPost": Route{
			"BroadcastPost",
			strings.ToUpper("Post"),
			"/broadcast",
			c.BroadcastPost,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the DefaultAPIController
func (c *DefaultAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"BalancesGet",
			strings.ToUpper("Get"),
			"/balances",
			c.BalancesGet,
		},
		Route{
			"TransactionsGet",
			strings.ToUpper("Get"),
			"/transactions",
			c.TransactionsGet,
		},
		Route{
			"UnsignedTxGet",
			strings.ToUpper("Get"),
			"/unsigned-tx",
			c.UnsignedTxGet,
		},
		Route{
			"BroadcastPost",
			strings.ToUpper("Post"),
			"/broadcast",
			c.BroadcastPost,
		},
	}
}



// BalancesGet - Get balances for multiple addresses and cryptocurrencies
func (c *DefaultAPIController) BalancesGet(w http.ResponseWriter, r *http.Request) {
	var balancesGetRequestParam BalancesGetRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&balancesGetRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBalancesGetRequestRequired(balancesGetRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBalancesGetRequestConstraints(balancesGetRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BalancesGet(r.Context(), balancesGetRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// TransactionsGet - Get transaction history for an address
func (c *DefaultAPIController) TransactionsGet(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var cryptoSymbolParam string
	if query.Has("crypto_symbol") {
		param := query.Get("crypto_symbol")

		cryptoSymbolParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "crypto_symbol"}, nil)
		return
	}
	var addressParam string
	if query.Has("address") {
		param := query.Get("address")

		addressParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "address"}, nil)
		return
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](100),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 50
		limitParam = param
	}
	var offsetParam int32
	if query.Has("offset") {
		param, err := parseNumericParameter[int32](
			query.Get("offset"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](0),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "offset", Err: err}, nil)
			return
		}

		offsetParam = param
	} else {
		var param int32 = 0
		offsetParam = param
	}
	result, err := c.service.TransactionsGet(r.Context(), cryptoSymbolParam, addressParam, limitParam, offsetParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UnsignedTxGet - Generate an unsigned transaction
func (c *DefaultAPIController) UnsignedTxGet(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var cryptoSymbolParam string
	if query.Has("crypto_symbol") {
		param := query.Get("crypto_symbol")

		cryptoSymbolParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "crypto_symbol"}, nil)
		return
	}
	var fromAddressParam string
	if query.Has("from_address") {
		param := query.Get("from_address")

		fromAddressParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "from_address"}, nil)
		return
	}
	var toAddressParam string
	if query.Has("to_address") {
		param := query.Get("to_address")

		toAddressParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "to_address"}, nil)
		return
	}
	var amountParam string
	if query.Has("amount") {
		param := query.Get("amount")

		amountParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "amount"}, nil)
		return
	}
	var feeRateParam float64
	if query.Has("fee_rate") {
		param, err := parseNumericParameter[float64](
			query.Get("fee_rate"),
			WithParse[float64](parseFloat64),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "fee_rate", Err: err}, nil)
			return
		}

		feeRateParam = param
	} else {
	}
	result, err := c.service.UnsignedTxGet(r.Context(), cryptoSymbolParam, fromAddressParam, toAddressParam, amountParam, feeRateParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BroadcastPost - Broadcast signed transaction
func (c *DefaultAPIController) BroadcastPost(w http.ResponseWriter, r *http.Request) {
	var broadcastPostRequestParam BroadcastPostRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&broadcastPostRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBroadcastPostRequestRequired(broadcastPostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBroadcastPostRequestConstraints(broadcastPostRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BroadcastPost(r.Context(), broadcastPostRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
