// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies, future-proof. 
 *
 * API version: 1.0.0
 */

package cryptowalletrest

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
