// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies, future-proof. 
 *
 * API version: 1.0.0
 */

package cryptowalletrest




type BalanceGet200Response struct {

	Crypto string `json:"crypto,omitempty"`

	Address string `json:"address,omitempty"`

	Balance float64 `json:"balance,omitempty"`
}

// AssertBalanceGet200ResponseRequired checks if the required fields are not zero-ed
func AssertBalanceGet200ResponseRequired(obj BalanceGet200Response) error {
	return nil
}

// AssertBalanceGet200ResponseConstraints checks if the values respects the defined constraints
func AssertBalanceGet200ResponseConstraints(obj BalanceGet200Response) error {
	return nil
}
