// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 
 *
 * API version: 1.0.2
 */

package cryptowalletrest




type BalancesGetRequestRequestsInner struct {

	// The cryptocurrency symbol (BTC, ETH, etc.)
	CryptoSymbol string `json:"crypto_symbol"`

	// The cryptocurrency address or xpub
	Address string `json:"address"`

	// The fiat currency symbol for conversion (USD, EUR, CAD, etc.)
	FiatSymbol string `json:"fiat_symbol,omitempty"`
}

// AssertBalancesGetRequestRequestsInnerRequired checks if the required fields are not zero-ed
func AssertBalancesGetRequestRequestsInnerRequired(obj BalancesGetRequestRequestsInner) error {
	elements := map[string]interface{}{
		"crypto_symbol": obj.CryptoSymbol,
		"address": obj.Address,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBalancesGetRequestRequestsInnerConstraints checks if the values respects the defined constraints
func AssertBalancesGetRequestRequestsInnerConstraints(obj BalancesGetRequestRequestsInner) error {
	return nil
}
