// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies, future-proof. 
 *
 * API version: 1.0.0
 */

package cryptowalletrest




type BroadcastPostRequest struct {

	// The cryptocurrency symbol
	Crypto string `json:"crypto,omitempty"`

	// Base64 / hex encoded signed transaction
	SignedTx string `json:"signedTx,omitempty"`
}

// AssertBroadcastPostRequestRequired checks if the required fields are not zero-ed
func AssertBroadcastPostRequestRequired(obj BroadcastPostRequest) error {
	return nil
}

// AssertBroadcastPostRequestConstraints checks if the values respects the defined constraints
func AssertBroadcastPostRequestConstraints(obj BroadcastPostRequest) error {
	return nil
}
