// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 
 *
 * API version: 1.0.1
 */

package cryptowalletrest




type BroadcastPostRequest struct {

	// The cryptocurrency symbol
	CryptoSymbol string `json:"crypto_symbol"`

	// Base64 or hex encoded signed transaction
	SignedTx string `json:"signed_tx"`
}

// AssertBroadcastPostRequestRequired checks if the required fields are not zero-ed
func AssertBroadcastPostRequestRequired(obj BroadcastPostRequest) error {
	elements := map[string]interface{}{
		"crypto_symbol": obj.CryptoSymbol,
		"signed_tx": obj.SignedTx,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBroadcastPostRequestConstraints checks if the values respects the defined constraints
func AssertBroadcastPostRequestConstraints(obj BroadcastPostRequest) error {
	return nil
}
