// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 
 *
 * API version: 1.0.2
 */

package cryptowalletrest


import (
	"time"
)



type Transaction struct {

	TransactionId string `json:"transaction_id"`

	BlockHeight int32 `json:"block_height,omitempty"`

	Timestamp time.Time `json:"timestamp"`

	Amount string `json:"amount"`

	Direction string `json:"direction"`

	Confirmations int32 `json:"confirmations"`

	FeeAmount string `json:"fee_amount,omitempty"`

	FromAddresses []string `json:"from_addresses,omitempty"`

	ToAddresses []string `json:"to_addresses,omitempty"`
}

// AssertTransactionRequired checks if the required fields are not zero-ed
func AssertTransactionRequired(obj Transaction) error {
	elements := map[string]interface{}{
		"transaction_id": obj.TransactionId,
		"timestamp": obj.Timestamp,
		"amount": obj.Amount,
		"direction": obj.Direction,
		"confirmations": obj.Confirmations,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTransactionConstraints checks if the values respects the defined constraints
func AssertTransactionConstraints(obj Transaction) error {
	return nil
}
