// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies, future-proof. 
 *
 * API version: 1.0.0
 */

package cryptowalletrest




type UnsignedTxGet200Response struct {

	Crypto string `json:"crypto,omitempty"`

	From string `json:"from,omitempty"`

	To string `json:"to,omitempty"`

	Amount string `json:"amount,omitempty"`

	// Base64 / hex encoded unsigned transaction or PSBT
	UnsignedTx string `json:"unsignedTx,omitempty"`
}

// AssertUnsignedTxGet200ResponseRequired checks if the required fields are not zero-ed
func AssertUnsignedTxGet200ResponseRequired(obj UnsignedTxGet200Response) error {
	return nil
}

// AssertUnsignedTxGet200ResponseConstraints checks if the values respects the defined constraints
func AssertUnsignedTxGet200ResponseConstraints(obj UnsignedTxGet200Response) error {
	return nil
}
