// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Crypto Wallet REST API
 *
 * REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies, future-proof. 
 *
 * API version: 1.0.0
 */

package cryptowalletrest




type BroadcastPost200Response struct {

	Crypto string `json:"crypto,omitempty"`

	Txid string `json:"txid,omitempty"`

	Status string `json:"status,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertBroadcastPost200ResponseRequired checks if the required fields are not zero-ed
func AssertBroadcastPost200ResponseRequired(obj BroadcastPost200Response) error {
	return nil
}

// AssertBroadcastPost200ResponseConstraints checks if the values respects the defined constraints
func AssertBroadcastPost200ResponseConstraints(obj BroadcastPost200Response) error {
	return nil
}
