// Code generated by MockGen. DO NOT EDIT.
// Source: ./openapi/servergen/go/helpers.go
//
// Generated by this command:
//
//	mockgen -source=./openapi/servergen/go/helpers.go -destination=mocks/openapiservergengo/openapiservergengohelpers.go -package=openapiservergengomocks
//

// Package openapiservergengomocks is a generated GoMock package.
package openapiservergengomocks
