// Code generated by MockGen. DO NOT EDIT.
// Source: ./openapi/clientgen/go/utils.go
//
// Generated by this command:
//
//	mockgen -source=./openapi/clientgen/go/utils.go -destination=mocks/openapiclientgengo/openapiclientgengoutils.go -package=openapiclientgengomocks
//

// Package openapiclientgengomocks is a generated GoMock package.
package openapiclientgengomocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMappedNullable is a mock of MappedNullable interface.
type MockMappedNullable struct {
	ctrl     *gomock.Controller
	recorder *MockMappedNullableMockRecorder
	isgomock struct{}
}

// MockMappedNullableMockRecorder is the mock recorder for MockMappedNullable.
type MockMappedNullableMockRecorder struct {
	mock *MockMappedNullable
}

// NewMockMappedNullable creates a new mock instance.
func NewMockMappedNullable(ctrl *gomock.Controller) *MockMappedNullable {
	mock := &MockMappedNullable{ctrl: ctrl}
	mock.recorder = &MockMappedNullableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappedNullable) EXPECT() *MockMappedNullableMockRecorder {
	return m.recorder
}

// ToMap mocks base method.
func (m *MockMappedNullable) ToMap() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToMap")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToMap indicates an expected call of ToMap.
func (mr *MockMappedNullableMockRecorder) ToMap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToMap", reflect.TypeOf((*MockMappedNullable)(nil).ToMap))
}
