/*
Crypto Wallet REST API

REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies, future-proof. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptowalletrest

import (
	"encoding/json"
)

// checks if the UnsignedTxGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnsignedTxGet200Response{}

// UnsignedTxGet200Response struct for UnsignedTxGet200Response
type UnsignedTxGet200Response struct {
	Crypto *string `json:"crypto,omitempty"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
	Amount *string `json:"amount,omitempty"`
	// Base64 / hex encoded unsigned transaction or PSBT
	UnsignedTx *string `json:"unsignedTx,omitempty"`
}

// NewUnsignedTxGet200Response instantiates a new UnsignedTxGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnsignedTxGet200Response() *UnsignedTxGet200Response {
	this := UnsignedTxGet200Response{}
	return &this
}

// NewUnsignedTxGet200ResponseWithDefaults instantiates a new UnsignedTxGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnsignedTxGet200ResponseWithDefaults() *UnsignedTxGet200Response {
	this := UnsignedTxGet200Response{}
	return &this
}

// GetCrypto returns the Crypto field value if set, zero value otherwise.
func (o *UnsignedTxGet200Response) GetCrypto() string {
	if o == nil || IsNil(o.Crypto) {
		var ret string
		return ret
	}
	return *o.Crypto
}

// GetCryptoOk returns a tuple with the Crypto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsignedTxGet200Response) GetCryptoOk() (*string, bool) {
	if o == nil || IsNil(o.Crypto) {
		return nil, false
	}
	return o.Crypto, true
}

// HasCrypto returns a boolean if a field has been set.
func (o *UnsignedTxGet200Response) HasCrypto() bool {
	if o != nil && !IsNil(o.Crypto) {
		return true
	}

	return false
}

// SetCrypto gets a reference to the given string and assigns it to the Crypto field.
func (o *UnsignedTxGet200Response) SetCrypto(v string) {
	o.Crypto = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *UnsignedTxGet200Response) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsignedTxGet200Response) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *UnsignedTxGet200Response) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *UnsignedTxGet200Response) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *UnsignedTxGet200Response) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsignedTxGet200Response) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *UnsignedTxGet200Response) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *UnsignedTxGet200Response) SetTo(v string) {
	o.To = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *UnsignedTxGet200Response) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsignedTxGet200Response) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *UnsignedTxGet200Response) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *UnsignedTxGet200Response) SetAmount(v string) {
	o.Amount = &v
}

// GetUnsignedTx returns the UnsignedTx field value if set, zero value otherwise.
func (o *UnsignedTxGet200Response) GetUnsignedTx() string {
	if o == nil || IsNil(o.UnsignedTx) {
		var ret string
		return ret
	}
	return *o.UnsignedTx
}

// GetUnsignedTxOk returns a tuple with the UnsignedTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsignedTxGet200Response) GetUnsignedTxOk() (*string, bool) {
	if o == nil || IsNil(o.UnsignedTx) {
		return nil, false
	}
	return o.UnsignedTx, true
}

// HasUnsignedTx returns a boolean if a field has been set.
func (o *UnsignedTxGet200Response) HasUnsignedTx() bool {
	if o != nil && !IsNil(o.UnsignedTx) {
		return true
	}

	return false
}

// SetUnsignedTx gets a reference to the given string and assigns it to the UnsignedTx field.
func (o *UnsignedTxGet200Response) SetUnsignedTx(v string) {
	o.UnsignedTx = &v
}

func (o UnsignedTxGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnsignedTxGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Crypto) {
		toSerialize["crypto"] = o.Crypto
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.UnsignedTx) {
		toSerialize["unsignedTx"] = o.UnsignedTx
	}
	return toSerialize, nil
}

type NullableUnsignedTxGet200Response struct {
	value *UnsignedTxGet200Response
	isSet bool
}

func (v NullableUnsignedTxGet200Response) Get() *UnsignedTxGet200Response {
	return v.value
}

func (v *NullableUnsignedTxGet200Response) Set(val *UnsignedTxGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUnsignedTxGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUnsignedTxGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnsignedTxGet200Response(val *UnsignedTxGet200Response) *NullableUnsignedTxGet200Response {
	return &NullableUnsignedTxGet200Response{value: val, isSet: true}
}

func (v NullableUnsignedTxGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnsignedTxGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


