/*
Crypto Wallet REST API

REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 

API version: 1.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptowalletrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BalancesGetRequestRequestsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalancesGetRequestRequestsInner{}

// BalancesGetRequestRequestsInner struct for BalancesGetRequestRequestsInner
type BalancesGetRequestRequestsInner struct {
	// The cryptocurrency symbol (BTC, ETH, etc.)
	CryptoSymbol string `json:"crypto_symbol"`
	// The cryptocurrency address or xpub
	Address string `json:"address"`
	// The fiat currency symbol for conversion (USD, EUR, CAD, etc.)
	FiatSymbol *string `json:"fiat_symbol,omitempty"`
}

type _BalancesGetRequestRequestsInner BalancesGetRequestRequestsInner

// NewBalancesGetRequestRequestsInner instantiates a new BalancesGetRequestRequestsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalancesGetRequestRequestsInner(cryptoSymbol string, address string) *BalancesGetRequestRequestsInner {
	this := BalancesGetRequestRequestsInner{}
	this.CryptoSymbol = cryptoSymbol
	this.Address = address
	var fiatSymbol string = "USD"
	this.FiatSymbol = &fiatSymbol
	return &this
}

// NewBalancesGetRequestRequestsInnerWithDefaults instantiates a new BalancesGetRequestRequestsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalancesGetRequestRequestsInnerWithDefaults() *BalancesGetRequestRequestsInner {
	this := BalancesGetRequestRequestsInner{}
	var fiatSymbol string = "USD"
	this.FiatSymbol = &fiatSymbol
	return &this
}

// GetCryptoSymbol returns the CryptoSymbol field value
func (o *BalancesGetRequestRequestsInner) GetCryptoSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CryptoSymbol
}

// GetCryptoSymbolOk returns a tuple with the CryptoSymbol field value
// and a boolean to check if the value has been set.
func (o *BalancesGetRequestRequestsInner) GetCryptoSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CryptoSymbol, true
}

// SetCryptoSymbol sets field value
func (o *BalancesGetRequestRequestsInner) SetCryptoSymbol(v string) {
	o.CryptoSymbol = v
}

// GetAddress returns the Address field value
func (o *BalancesGetRequestRequestsInner) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *BalancesGetRequestRequestsInner) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *BalancesGetRequestRequestsInner) SetAddress(v string) {
	o.Address = v
}

// GetFiatSymbol returns the FiatSymbol field value if set, zero value otherwise.
func (o *BalancesGetRequestRequestsInner) GetFiatSymbol() string {
	if o == nil || IsNil(o.FiatSymbol) {
		var ret string
		return ret
	}
	return *o.FiatSymbol
}

// GetFiatSymbolOk returns a tuple with the FiatSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalancesGetRequestRequestsInner) GetFiatSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.FiatSymbol) {
		return nil, false
	}
	return o.FiatSymbol, true
}

// HasFiatSymbol returns a boolean if a field has been set.
func (o *BalancesGetRequestRequestsInner) HasFiatSymbol() bool {
	if o != nil && !IsNil(o.FiatSymbol) {
		return true
	}

	return false
}

// SetFiatSymbol gets a reference to the given string and assigns it to the FiatSymbol field.
func (o *BalancesGetRequestRequestsInner) SetFiatSymbol(v string) {
	o.FiatSymbol = &v
}

func (o BalancesGetRequestRequestsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalancesGetRequestRequestsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["crypto_symbol"] = o.CryptoSymbol
	toSerialize["address"] = o.Address
	if !IsNil(o.FiatSymbol) {
		toSerialize["fiat_symbol"] = o.FiatSymbol
	}
	return toSerialize, nil
}

func (o *BalancesGetRequestRequestsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"crypto_symbol",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBalancesGetRequestRequestsInner := _BalancesGetRequestRequestsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBalancesGetRequestRequestsInner)

	if err != nil {
		return err
	}

	*o = BalancesGetRequestRequestsInner(varBalancesGetRequestRequestsInner)

	return err
}

type NullableBalancesGetRequestRequestsInner struct {
	value *BalancesGetRequestRequestsInner
	isSet bool
}

func (v NullableBalancesGetRequestRequestsInner) Get() *BalancesGetRequestRequestsInner {
	return v.value
}

func (v *NullableBalancesGetRequestRequestsInner) Set(val *BalancesGetRequestRequestsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBalancesGetRequestRequestsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBalancesGetRequestRequestsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalancesGetRequestRequestsInner(val *BalancesGetRequestRequestsInner) *NullableBalancesGetRequestRequestsInner {
	return &NullableBalancesGetRequestRequestsInner{value: val, isSet: true}
}

func (v NullableBalancesGetRequestRequestsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalancesGetRequestRequestsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


