/*
Crypto Wallet REST API

REST API for air-gapped crypto wallets. Supports multiple cryptocurrencies with fiat currency conversion, future-proof. 

API version: 1.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptowalletrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BalancesGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalancesGetRequest{}

// BalancesGetRequest struct for BalancesGetRequest
type BalancesGetRequest struct {
	Requests []BalancesGetRequestRequestsInner `json:"requests"`
	// Default fiat currency symbol for all requests if not specified individually
	FiatSymbol *string `json:"fiat_symbol,omitempty"`
}

type _BalancesGetRequest BalancesGetRequest

// NewBalancesGetRequest instantiates a new BalancesGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalancesGetRequest(requests []BalancesGetRequestRequestsInner) *BalancesGetRequest {
	this := BalancesGetRequest{}
	this.Requests = requests
	var fiatSymbol string = "USD"
	this.FiatSymbol = &fiatSymbol
	return &this
}

// NewBalancesGetRequestWithDefaults instantiates a new BalancesGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalancesGetRequestWithDefaults() *BalancesGetRequest {
	this := BalancesGetRequest{}
	var fiatSymbol string = "USD"
	this.FiatSymbol = &fiatSymbol
	return &this
}

// GetRequests returns the Requests field value
func (o *BalancesGetRequest) GetRequests() []BalancesGetRequestRequestsInner {
	if o == nil {
		var ret []BalancesGetRequestRequestsInner
		return ret
	}

	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value
// and a boolean to check if the value has been set.
func (o *BalancesGetRequest) GetRequestsOk() ([]BalancesGetRequestRequestsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requests, true
}

// SetRequests sets field value
func (o *BalancesGetRequest) SetRequests(v []BalancesGetRequestRequestsInner) {
	o.Requests = v
}

// GetFiatSymbol returns the FiatSymbol field value if set, zero value otherwise.
func (o *BalancesGetRequest) GetFiatSymbol() string {
	if o == nil || IsNil(o.FiatSymbol) {
		var ret string
		return ret
	}
	return *o.FiatSymbol
}

// GetFiatSymbolOk returns a tuple with the FiatSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BalancesGetRequest) GetFiatSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.FiatSymbol) {
		return nil, false
	}
	return o.FiatSymbol, true
}

// HasFiatSymbol returns a boolean if a field has been set.
func (o *BalancesGetRequest) HasFiatSymbol() bool {
	if o != nil && !IsNil(o.FiatSymbol) {
		return true
	}

	return false
}

// SetFiatSymbol gets a reference to the given string and assigns it to the FiatSymbol field.
func (o *BalancesGetRequest) SetFiatSymbol(v string) {
	o.FiatSymbol = &v
}

func (o BalancesGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalancesGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requests"] = o.Requests
	if !IsNil(o.FiatSymbol) {
		toSerialize["fiat_symbol"] = o.FiatSymbol
	}
	return toSerialize, nil
}

func (o *BalancesGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBalancesGetRequest := _BalancesGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBalancesGetRequest)

	if err != nil {
		return err
	}

	*o = BalancesGetRequest(varBalancesGetRequest)

	return err
}

type NullableBalancesGetRequest struct {
	value *BalancesGetRequest
	isSet bool
}

func (v NullableBalancesGetRequest) Get() *BalancesGetRequest {
	return v.value
}

func (v *NullableBalancesGetRequest) Set(val *BalancesGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBalancesGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBalancesGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalancesGetRequest(val *BalancesGetRequest) *NullableBalancesGetRequest {
	return &NullableBalancesGetRequest{value: val, isSet: true}
}

func (v NullableBalancesGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalancesGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


